# Block for general settings.
library: general
settings:
    # Time until a timeout in seconds.
    timeout: 9000
    database: 'reports/benchmark.db'
    keepReports: 20
---
library: scikit
methods:
    NBC:
        run: ['timing', 'metric']
        iteration: 3
        script: methods/scikit/nbc.py
        format: [csv, txt]
        datasets:
            # We need to add a new dataset to evaluate the classifiers 
            # prediction. One way to achive that is to add a file, that contains
            # the true labels of the test set.
            - files: [ ['datasets/iris_train.csv', 'datasets/iris_test.csv', 'datasets/iris_labels.csv'] ]