# Block for general settings.
library: general
settings:
    # Time until a timeout in seconds.
    timeout: 9000
    database: 'reports/benchmark.db'
    keepReports: 20
---
# MLPACK:
# A Scalable C++  Machine Learning Library
library: mlpack
methods:
    NBC:
        run: true
        iteration: 3
        script: methods/mlpack/nbc.py
        format: [csv, txt]
        datasets:
            # We need to add a new dataset to evaluate the classifiers 
            # prediction. One way to achive that is to add a file, that contains
            # the true labels of the test set.
            - files: [ ['datasets/iris_train.csv', 'datasets/iris_test.csv', 'datasets/iris_train.csv'],
                       ['datasets/transfusion_train.csv', 'datasets/transfusion_test.csv', 'datasets/transfusion_train.csv'] ]