# Block for general settings.
library: general
settings:
    # Time until a timeout in seconds.
    timeout: 500
    database: 'reports/benchmark.db'
    keepReports: 20
    libraries: ['mlpack']
    version: ['1.0.10']
---
# MLPACK:
# A Scalable C++  Machine Learning Library
library: mlpack
methods:
    PCA:
        run: ['timing']
        iteration: 3
        script: methods/mlpack/pca.py
        format: [csv, txt]
        datasets:
            - files: ['datasets/cities.csv', 'datasets/faces.csv', 'datasets/iris.csv' ]

    KMEANS:
        run: ['timing']
        iteration: 3
        script: methods/mlpack/kmeans.py
        format: [csv, txt]
        datasets:
            - files: [ ['datasets/wine.csv', 'datasets/wine_centroids.csv'],
                       ['datasets/iris.csv', 'datasets/iris_centroids.csv'] ]
              options: '-c 3'
    ALLKNN:
        run: ['timing']
        iteration: 3
        script: methods/mlpack/allknn.py
        format: [csv, txt]
        datasets:
            - files: ['datasets/wine.csv', 'datasets/cloud.csv', 'datasets/pendigits.csv']
              options: '-k 3 -s 42'

    LinearRegression:
        run: ['timing']
        iteration: 3
        script: methods/mlpack/linear_regression.py
        format: [csv, txt]
        datasets:
             - files: [ ['datasets/diabetes_X.csv'], ['datasets/cosExp_X.csv'],
                        ['datasets/madelon_train.csv', 'datasets/madelon_test.csv'],
                        ['datasets/arcene_train.csv', 'datasets/arcene_test.csv'] ]
